# Generated by Django 5.0.4 on 2024-08-03 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostWatchedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('published_date', models.DateTimeField(default=datetime.datetime(2024, 8, 3, 19, 20, 15, 760097))),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
