# Generated by Django 5.0.4 on 2024-06-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
