# Generated by Django 4.1.5 on 2024-06-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porfoliocomp',
            old_name='Percentage',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='porfoliocomp',
            old_name='portifolio',
            new_name='portfolio',
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(),
        ),
    ]
