# Generated by Django 5.0.4 on 2024-06-18 05:03

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='assets.operation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfoliocomp',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.expressions.Case, related_name='portfolio', to='assets.portfolio'),
        ),
    ]
