# Generated by Django 5.0.4 on 2024-07-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_trade_operator_alter_portfoliocomp_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetPrice', to='assets.asset')),
            ],
        ),
    ]
