# Generated by Django 4.1.5 on 2024-07-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalviewsmodel',
            name='views',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
