# Generated by Django 4.1.5 on 2024-07-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_totalviewsmodel_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalViewsModel',
        ),
    ]
